on: push
#  push:
#    branches:
#      - dev

name: Deploy to Heroku - Dev to Stagging
jobs:
  deploy_api:
    name: Deploy Api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build frontend
        run: |
          cd pwa
          npm install
          npm run build
          mkdir -p ../api/public
          mv build/* ../api/public
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: /api/public

      - name: Push to Heroku remote
        id: build-image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_APP_NAME: "computers-4-all-staging"
        run: |
          pwd
          ls
          heroku login
          heroku git:remote -a $HEROKU_APP_NAME
          git subtree push --prefix api heroku master
