on: push
#on: pull_request

name: ESLint check - Dev branch
jobs:
  eslit_check:
    name: Deploy Api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "11.x"

      - name: API - Cache node modules
        id: api-cache-node-modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: api-${{ runner.os }}-node_modules-${{ hashFiles('api/package-lock.json') }}

      - name: API - Install Dependencies
        run: cd api && npm ci

      - name: API - Prettier
        run: cd api && npm run prettier

      - name: API - ESlint
        run: cd api && npm run lint
