on: pull_request

name: ESLint and Prettier check - Dev branch
jobs:
  api_eslit_prettier_check:
    name: API - ESLint and Prettier check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "11.x"

      - name: API - Cache node modules
        id: api-cache-node-modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: api-${{ runner.os }}-node_modules-${{ hashFiles('api/package-lock.json') }}

      - name: API - Install Dependencies
        run: cd api && npm ci

      - name: API - Prettier
        run: cd api && npm run prettier

      - name: API - ESlint
        run: cd api && npm run lint

  pwa_eslit_prettier_check:
    name: PWA - ESLint and Prettier check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "11.x"

      - name: PWA - Cache node modules
        id: pwa-cache-node-modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: pwa-${{ runner.os }}-node_modules-${{ hashFiles('pwa/package-lock.json') }}

      - name: PWA - Install Dependencies
        run: cd pwa && npm ci

      - name: PWA - Prettier
        run: cd pwa && npm run prettier

      - name: PWA - ESlint
        run: cd pwa && npm run lint
